version: '3.8'

services:
  backend-api:
    build: ./app/api
    container_name: backend-api
    ports:
      - "8000:8000"
    depends_on:
      - ml-model
    networks:
      - app-network

  frontend:
    build: ./app/stock-prediction-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-api
    networks:
      - app-network

  ml-model:
    build: ./src
    container_name: ml-model
    volumes:
      - ./data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge